### ISSUE TITLE
ChoiceType column doesn't result in a field

### ISSUE THREAD

**Issue by thejcannon** [graphql-python/graphene-sqlalchemy#199] opened 2019-04-01 22:10 UTC
Given
```py
class MyModel(Base):
   foo = Column(ChoiceType([('X', 1)])

class MyModelNode(SQLAlchemyObjectType):
   class Meta:
      model= MyModel
```

I'm missing "foo" from the generated schema.

I believe this is due to the fact that `convert_column_to_enum` is returning an instance of `graphene.Enum`, which isn't a `MountedScalar` or a `Field` (notice `convert_enum_to_enum` returns a `Field`)

**Comment by thejcannon** [comment] 2019-04-02 13:51
Actually, this seems to be an issue with `graphene-python`. From the code `graphene.ENum` _should_ be able to be mounted (like a scalar), but instances of `graphene.Enum` are failing `isinstance(enum, UnmountedType)` which means the enum instance isn't being mounted.

**Comment by thejcannon** [comment] 2019-04-02 13:55
Now it's getting really weird.
```py
>>> isinstance(Enum('Foo', [('X', 1)]), UnmountedType)
False
>>> isinstance(Int(), UnmountedType)
True
>>> isinstance(Enum('Foo', [('X', 1)])(), UnmountedType)
True
```

**Comment by thejcannon** [comment] 2019-04-02 14:08
OK I created an issue with `graphene-python` about this.

**Comment by thejcannon** [comment] 2019-04-02 14:09
Didn't mean to close 😄 (as there might be consequences that affect this library from the outcome of the other issue)

**Comment by squarewave24** [comment] 2020-05-28 16:01
is there another thread with a resolution? 
i'm on 2.2.2 and still bumping into this issue :(

**Comment by erikwrede** [comment] 2022-08-12 21:20
Issue can't be reproduced on `master`. Seems to be fixed. 
This issue is 2 years old so I'm closing it.
@squarewave24  if you have found [and still need] a fix for 2.x, I'd happily push another release for the affected version if you open a PR!

**Closed by erikwrede** 2022-08-12 21:20 UTC
Labels: bug, waiting
