### ISSUE TITLE
singledispatch is not necessary for python_version >= Python3.4

### ISSUE THREAD

**Issue by smfoote** [graphql-python/graphene-sqlalchemy#182] opened 2019-01-22 21:14 UTC
I am using Python 3.7 and the attempt to install singledispatch is causing my build to break. I believe the way to resolve this issue is by using [conditional dependencies](https://hynek.me/articles/conditional-python-dependencies/) as outlined in [PEP 508](https://www.python.org/dev/peps/pep-0508/). I will follow up with a PR shortly.

**Comment by Nabellaleen** [comment] 2019-03-18 09:34
Hi @smfoote !

Could you give us more details about the error you get on building ? I don't reproduce, as singledispatch backport is working well on 3.7

**Comment by jnak** [comment] 2020-02-12 02:07
Closing for now since we haven't gotten the details requested.

**Closed by jnak** 2020-02-12 02:07 UTC
Labels: :eyes: more info needed, bug

**Comment by JBrVJxsc** [comment] 2021-05-07 19:21
having the same issue here as well ```         from graphene_sqlalchemy.converter import convert_sqlalchemy_type
     ../build/lipy-graphql-sqlalchemy/environments_3.6/satellites/python/lib/python3.6/site-packages/graphene_sqlalchemy/__init__.py:1: in <module>
         from .types import SQLAlchemyObjectType
     ../build/lipy-graphql-sqlalchemy/environments_3.6/satellites/python/lib/python3.6/site-packages/graphene_sqlalchemy/types.py:15: in <module>
         from .converter import (convert_sqlalchemy_column,
     ../build/lipy-graphql-sqlalchemy/environments_3.6/satellites/python/lib/python3.6/site-packages/graphene_sqlalchemy/converter.py:3: in <module>
         from singledispatch import singledispatch
     E   ModuleNotFoundError: No module named 'singledispatch'
```

**Comment by erikwrede** [comment] 2022-04-28 16:29
This is resolved in 3.0-Beta. The singledispatch dependency was removed since support for python < 3.6 was dropped.
